/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IOVMChainStorageContainerInterface extends ethers.utils.Interface {
  functions: {
    "deleteElementsAfterInclusive(uint256,bytes27)": FunctionFragment;
    "get(uint256)": FunctionFragment;
    "getGlobalMetadata()": FunctionFragment;
    "length()": FunctionFragment;
    "push(bytes32,bytes27)": FunctionFragment;
    "push2(bytes32,bytes32,bytes27)": FunctionFragment;
    "setGlobalMetadata(bytes27)": FunctionFragment;
    "setNextOverwritableIndex(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deleteElementsAfterInclusive",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "get", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getGlobalMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "push",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "push2",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalMetadata",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNextOverwritableIndex",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteElementsAfterInclusive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "push", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "push2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNextOverwritableIndex",
    data: BytesLike
  ): Result;

  events: {};
}

export class IOVMChainStorageContainer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IOVMChainStorageContainerInterface;

  functions: {
    "deleteElementsAfterInclusive(uint256,bytes27)"(
      _index: BigNumberish,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deleteElementsAfterInclusive(uint256)"(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    get(_index: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    "get(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getGlobalMetadata(overrides?: CallOverrides): Promise<[string]>;

    "getGlobalMetadata()"(overrides?: CallOverrides): Promise<[string]>;

    length(overrides?: CallOverrides): Promise<[BigNumber]>;

    "length()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    "push(bytes32,bytes27)"(
      _object: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "push(bytes32)"(
      _object: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "push2(bytes32,bytes32,bytes27)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "push2(bytes32,bytes32)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGlobalMetadata(
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setGlobalMetadata(bytes27)"(
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNextOverwritableIndex(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setNextOverwritableIndex(uint256)"(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "deleteElementsAfterInclusive(uint256,bytes27)"(
    _index: BigNumberish,
    _globalMetadata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deleteElementsAfterInclusive(uint256)"(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  get(_index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "get(uint256)"(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getGlobalMetadata(overrides?: CallOverrides): Promise<string>;

  "getGlobalMetadata()"(overrides?: CallOverrides): Promise<string>;

  length(overrides?: CallOverrides): Promise<BigNumber>;

  "length()"(overrides?: CallOverrides): Promise<BigNumber>;

  "push(bytes32,bytes27)"(
    _object: BytesLike,
    _globalMetadata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "push(bytes32)"(
    _object: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "push2(bytes32,bytes32,bytes27)"(
    _objectA: BytesLike,
    _objectB: BytesLike,
    _globalMetadata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "push2(bytes32,bytes32)"(
    _objectA: BytesLike,
    _objectB: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGlobalMetadata(
    _globalMetadata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setGlobalMetadata(bytes27)"(
    _globalMetadata: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNextOverwritableIndex(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setNextOverwritableIndex(uint256)"(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "deleteElementsAfterInclusive(uint256,bytes27)"(
      _index: BigNumberish,
      _globalMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "deleteElementsAfterInclusive(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    get(_index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "get(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getGlobalMetadata(overrides?: CallOverrides): Promise<string>;

    "getGlobalMetadata()"(overrides?: CallOverrides): Promise<string>;

    length(overrides?: CallOverrides): Promise<BigNumber>;

    "length()"(overrides?: CallOverrides): Promise<BigNumber>;

    "push(bytes32,bytes27)"(
      _object: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "push(bytes32)"(
      _object: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "push2(bytes32,bytes32,bytes27)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "push2(bytes32,bytes32)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setGlobalMetadata(
      _globalMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "setGlobalMetadata(bytes27)"(
      _globalMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setNextOverwritableIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setNextOverwritableIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    "deleteElementsAfterInclusive(uint256,bytes27)"(
      _index: BigNumberish,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deleteElementsAfterInclusive(uint256)"(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    get(_index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "get(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGlobalMetadata(overrides?: CallOverrides): Promise<BigNumber>;

    "getGlobalMetadata()"(overrides?: CallOverrides): Promise<BigNumber>;

    length(overrides?: CallOverrides): Promise<BigNumber>;

    "length()"(overrides?: CallOverrides): Promise<BigNumber>;

    "push(bytes32,bytes27)"(
      _object: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "push(bytes32)"(
      _object: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "push2(bytes32,bytes32,bytes27)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "push2(bytes32,bytes32)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGlobalMetadata(
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setGlobalMetadata(bytes27)"(
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNextOverwritableIndex(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setNextOverwritableIndex(uint256)"(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "deleteElementsAfterInclusive(uint256,bytes27)"(
      _index: BigNumberish,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deleteElementsAfterInclusive(uint256)"(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    get(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "get(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGlobalMetadata(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getGlobalMetadata()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    length(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "length()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "push(bytes32,bytes27)"(
      _object: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "push(bytes32)"(
      _object: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "push2(bytes32,bytes32,bytes27)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "push2(bytes32,bytes32)"(
      _objectA: BytesLike,
      _objectB: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGlobalMetadata(
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setGlobalMetadata(bytes27)"(
      _globalMetadata: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNextOverwritableIndex(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setNextOverwritableIndex(uint256)"(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
