/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IOVML1MessageSenderInterface extends ethers.utils.Interface {
  functions: {
    "getL1MessageSender()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getL1MessageSender",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getL1MessageSender",
    data: BytesLike
  ): Result;

  events: {};
}

export class IOVML1MessageSender extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IOVML1MessageSenderInterface;

  functions: {
    getL1MessageSender(
      overrides?: CallOverrides
    ): Promise<[string] & { _l1MessageSender: string }>;

    "getL1MessageSender()"(
      overrides?: CallOverrides
    ): Promise<[string] & { _l1MessageSender: string }>;
  };

  getL1MessageSender(overrides?: CallOverrides): Promise<string>;

  "getL1MessageSender()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getL1MessageSender(overrides?: CallOverrides): Promise<string>;

    "getL1MessageSender()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getL1MessageSender(overrides?: CallOverrides): Promise<BigNumber>;

    "getL1MessageSender()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getL1MessageSender(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getL1MessageSender()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
